### ISSUE TITLE
Sprites não carregadas

### ISSUE THREAD

**Issue by PedroLucasMF** [Lucianolpsf/pokedex#1]
boa tarde
Após o Pokémon de numero 649 - Genesect, todos os outros em seguida dele não estão carregando seus sprites, procurei o sprite do pokemon de numero 650 - chespin na API e lá o sprite está endereçado corretamente, irei procurar em seu codigo onde possa está o erro que está causando esta falha no carregamento de sprites

**Comment by Lucianolpsf** [comment]
Opa, obrigado por notar, agradeço e aguardo sua solução. :-)
